ARG BUN_VERSION=1.2.12-alpine

FROM oven/bun:${BUN_VERSION} AS base

FROM base AS deps

WORKDIR /tmp

COPY prisma prisma
COPY package.json .
COPY bun.lock .

CMD ["bunx", "prisma", "migrate", "deploy"]