ARG BUN_VERSION=1.2.2

FROM oven/bun:${BUN_VERSION} AS base

FROM base AS deps

WORKDIR /tmp

COPY package.json .
COPY bun.lock .

RUN bun install --frozen-lockfile

FROM gcr.io/distroless/nodejs22-debian12 AS prestart

WORKDIR /tmp

COPY --from=deps /tmp/node_modules/prisma ./node_modules/prisma
COPY --from=deps /tmp/node_modules/@prisma ./node_modules/@prisma

COPY prisma prisma

CMD [ "./node_modules/prisma/build/index.js", "migrate", "deploy" ]